version: '3.10'
services:
  server:
    container_name: whatsapp-api
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./:usr/src
      - /usr/src/app/node_modules
    env_file:
      - .env
    ports:
      - '3000:3000'
